Doc: Updates to site style and addition of vale
aristanetworks/openmgmt pull request #119
Opened 2022-10-21 19:41 UTC by JulioPDX

Added or corrected the following:

- Add [Vale](https://github.com/errata-ai/vale-action) linting to CI based on Google style
- Add Arista favicon icon to site
- Minor corrections on spacing and spelling
- Add minor CSS for site theme
- Enabled social icon for GitHub and Global site
- Enabled code block highlighting

2022-10-21 19:41 UTC, JulioPDX commented
Please let me know if Vale is a little much, I can always remove it. Thank you

2022-10-22 15:57 UTC, sulrich requested changes
- candidly, i think the vale addition is a (bit of a) reach too far. we've had enough challenges getting folks to pass the standard linting processes.  though the integration checks have helped enforcement on this.  grammar/style checks seem almost punitive. 😉 
- love the style updates

2022-10-24 17:59 UTC, JulioPDX commented on docs/examples/gnmi-clients/gnmic/index.md
> -gnmi -addr 192.0.2.139 -username admin get \
That would be good. Makes it easier for the user running through the examples. Vs editing each command for their environment.

2022-10-24 18:01 UTC, JulioPDX commented
@sulrich Just removed the vale additions. Thank you for the feedback

2022-10-24 18:35 UTC, sulrich approved these changes

2022-10-24 18:35 UTC, merged