a rather large mkdocs driven refactor
aristanetworks/openmgmt pull request #39
Opened 2021-07-09 22:45 UTC by sulrich

a rather large refactoring

this consolidates the following items: 
- removes unused/unreferenced documents from the repo (this was historic cruft)
- moves sample code in the examples hierarchy into a new portion of the repo
  (src) such that it can be referenced and updated. however, as an interim
  measure, the contents of the sample code has been pulled into the markdown
  files referencing it.
- refactors the configuration section to treat OC/NETCONF/RESTCONF as directly
  addressable topics. adds a certificate authentication section (new)
- removes the TOC from pages that had it. (this is automatically generated by
  mkdocs)
- adds a nav section to the mkdocs.yml file to only reference the docs sections
  with content.

2021-07-09 23:03 UTC, sulrich reviewed
i broke the configuration document up into 5 documents. 
- openconfig
- certificate auth (net new)
- RESTCONF
- NETCONF
- security

the openconfig elements which were previously interrupted by the NET/RESTCONF elements are now consolidated and read a little more cohesively.  the security document is effectively just the service acl elements and can be referenced more consistently.

2021-07-09 23:03 UTC, sulrich commented on docs/examples/ansible/index.md
> -- [Ansible collections for](#overview)
TOCs are now generated by mkdocs.  this eliminates the need to generate these internal to the document.

2021-07-09 23:11 UTC, fredhsu commented on docs/configuration/security.md
> +sysem control-plane
typo on 'system control-plane'

2021-07-09 23:11 UTC, fredhsu commented on docs/configuration/security.md
> +sysem control-plane
typo on 'system control-plane'

2021-07-09 23:13 UTC, fredhsu requested changes
Found a couple minor typos, otherwise LGTM, thanks for all the cleanup! @sulrich I rendered on my local machine and it all looks good

2021-07-10 01:00 UTC, sulrich commented on docs/configuration/security.md
> +sysem control-plane
ack - thanks!

2021-07-10 01:01 UTC, sulrich commented on docs/configuration/security.md
> +sysem control-plane
ack - thanks!

2021-07-12 17:13 UTC, fredhsu approved these changes

2021-07-12 18:20 UTC, sulrich commented on docs/configuration/openconfig.md
> +The OpenConfing agent (gNMI API) can leverage the EOS state streaming agent's (TerminAttr) libraries, thus exposing EOS
got it. thanks!

2021-07-12 22:33 UTC, merged